// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4r1E8PExWvnJEck_bhHDcDBCoQQ2OjXU',
    appId: '1:464882402082:web:7c3bbb61419c2540765b7b',
    messagingSenderId: '464882402082',
    projectId: 'trying-410a0',
    authDomain: 'trying-410a0.firebaseapp.com',
    storageBucket: 'trying-410a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfN8ThMCXdOe59se4XdI-VQTYbNqiCDKg',
    appId: '1:464882402082:android:191df50a848b8505765b7b',
    messagingSenderId: '464882402082',
    projectId: 'trying-410a0',
    storageBucket: 'trying-410a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4I4WfhBcx7ixLx4VguChm-n2y8ZKoOME',
    appId: '1:464882402082:ios:fd60652f55614b90765b7b',
    messagingSenderId: '464882402082',
    projectId: 'trying-410a0',
    storageBucket: 'trying-410a0.appspot.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4I4WfhBcx7ixLx4VguChm-n2y8ZKoOME',
    appId: '1:464882402082:ios:fd60652f55614b90765b7b',
    messagingSenderId: '464882402082',
    projectId: 'trying-410a0',
    storageBucket: 'trying-410a0.appspot.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4r1E8PExWvnJEck_bhHDcDBCoQQ2OjXU',
    appId: '1:464882402082:web:99ec05cf911b79a0765b7b',
    messagingSenderId: '464882402082',
    projectId: 'trying-410a0',
    authDomain: 'trying-410a0.firebaseapp.com',
    storageBucket: 'trying-410a0.appspot.com',
  );
}
